GITHUB_USER = '<your username>'
GITHUB_TOKEN = '<your token>'

BOT_COMMENT_BODY_TEMPLATE = '''## Downloads for this pull request\n\n'''
BOT_COMMENT_DOWNLOAD_LINE_TEMPLATE = "- {platform}: [download]({link}).\n"
BOT_COMMENT_FOOTER = '\n\nGenerated by the [LMMS pull requests bot]' \
                     '(https://github.com/lmms/bot/).'

EXTENSION_TO_PLATFORM_TITLE = {
    'dmg': "Mac",
    'AppImage': "Linux",
    'win32.exe': "Windows 32 Bit",
    'win64.exe': "Windows 64 Bit",
}
